version: "3.9"
services:
  i-audit-node-app:
    # this build uses the Dockerfile to create an image
    build: ../../node-app
    image: i-audit-v1-img-node-app
    container_name: i-audit-v1-container-node-app
    hostname: i-audit-v1-node-app
    ports:
      - "8080:8080"
    networks:
      - i-audit


networks:
  i-audit:
    name: i-audit-v1
    driver: bridge