version: "3.9"
services:
  mysql-i-audit:
    # this container uses an image from docker hub using "docker pull" command under the hood
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql-i-audit
    hostname: mysql-i-audit
    ports:
      - "3307:3306"
    networks:
      - i-audit
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  i-audit:
    name: i-audit
    driver: bridge
